name: Tests - Python

on:
  pull_request:
    paths:
      - '.github/workflows/python-tests.yml'
      - 'python/**'
  push:
    branches:
      - "*"
    paths:
      - '.github/workflows/python-tests.yml'
      - 'python/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: macOS install dependencies
        if: runner.os == 'macOS'
        run: |
          brew install tesseract
          brew install --cask android-platform-tools


      - name: Install uv
        run: python -m pip install uv

      - name: Run Pytests with coverage
        working-directory: python
        run: uv run pytest --maxfail=1 --disable-warnings --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: AdbAutoPlayer/AdbAutoPlayer
          flags: ${{ matrix.os }}
